name: Test
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  Run_Tests:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: exec ./.github/scripts/test_app.sh 
