name: Test
on:
  pull_request:
    types: [opened, synchronize]
  release:
    types: [prereleased]
  push:
    branches:
      - 'master'
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  Run_Tests:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.app && /usr/bin/xcodebuild -version

    - name: List Simulators
      run: xcrun simctl list runtimes

    - name: Test iOS app
      run: |
        xcodebuild \
          -project RecurlySDK-iOS.xcodeproj \
          -scheme RecurlySDK-iOS \
          -destination 'platform=iOS Simulator,name=iPhone 13' \
          PUBLIC_KEY=$API_TOKEN \
          test \
