name: Swift
on: [push, pull_request]
jobs:
  Run_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app && /usr/bin/xcodebuild -version
    - name: find project
      run: xcodebuild test -list -project
    - name: find workspace
      run: xcodebuild test -list -workspace 
    - name: Run unit tests
      run: xcodebuild test -scheme RecurlySDK-iOS -workspace RecurlySDK-iOS.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' | xcpretty && exit ${PIPESTATUS[0]} 
